PARAMFLOAT(amount, 0.25, "Amount", "Denoising amount", 0, 1)
PARAMFLOAT(luminance, 0, "Luminance", "Amount to apply to luminance", 0, 1)
PARAMFLOAT(color, 1, "Color", "Amount to apply to color", 0, 1)
PARAMFLOAT(width, 8, "Width", "Kernel size of filter", 1, 8)
PARAMCOUNT(count)