PARAMFLOAT(rscaler, 1, "R scale R", "Red channel red amount")
PARAMFLOAT(rscaleg, 0, "R scale G", "Red channel green amount")
PARAMFLOAT(rscaleb, 0, "R scale B", "Red channel blue amount")
PARAMFLOAT(gscaler, 0, "G scale R", "Green channel red amount")
PARAMFLOAT(gscaleg, 1, "G scale G", "Green channel green amount")
PARAMFLOAT(gscaleb, 0, "G scale B", "Green channel blue amount")
PARAMFLOAT(bscaler, 0, "B scale R", "Blue channel red amount")
PARAMFLOAT(bscaleg, 0, "B scale G", "Blue channel green amount")
PARAMFLOAT(bscaleb, 1, "B scale B", "Blue channel blue amount")
PARAMFLOAT(preserveLum, 0, "Preserve Luminance", "Zero to use scales directly, One to post-scale back to the same luminance")
PARAMCOUNT(count)